const DOMSelectors = {
  all: document.getElementById("all"),
  female: document.getElementById("female"),
  male: document.getElementById("male"),
  pyro: document.getElementById("pyro"),
  hydro: document.getElementById("hydro"),
  cyro: document.getElementById("cyro"),
  anemo: document.getElementById("anemo"),
  electro: document.getElementById("electro"),
  dendro: document.getElementById("dendro"),
  geo: document.getElementById("geo"),
  bow: document.getElementById("bow"),
  catalyst: document.getElementById("catalyst"),
  claymore: document.getElementById("claymore"),
  sword: document.getElementById("sword"),
  polearm: document.getElementById("polearm"),
  mondstadt: document.getElementById("mondstadt"),
  liyue: document.getElementById("liyue"),
  inazuma: document.getElementById("inazuma"),
  sumeru: document.getElementById("sumeru"),
  text: document.querySelector("text"),
};
export { DOMSelectors };
